# coding: utf-8

"""
    NewsRank API

    The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from newsrank_sdk.models.article_content_tags_inner import ArticleContentTagsInner
from typing import Optional, Set
from typing_extensions import Self

class ArticleContent(BaseModel):
    """
    ArticleContent
    """ # noqa: E501
    ok: Optional[StrictBool] = None
    url_hash: Optional[StrictStr] = None
    final_url: Optional[StrictStr] = None
    image_url: Optional[StrictStr] = None
    thumb_url: Optional[StrictStr] = None
    video_url: Optional[StrictStr] = None
    extracted_title: Optional[StrictStr] = None
    text: Optional[StrictStr] = None
    extracted_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp in milliseconds")
    truncated: Optional[StrictBool] = None
    headline_summary: Optional[StrictStr] = None
    full_summary: Optional[StrictStr] = None
    tags: Optional[List[ArticleContentTagsInner]] = None
    __properties: ClassVar[List[str]] = ["ok", "url_hash", "final_url", "image_url", "thumb_url", "video_url", "extracted_title", "text", "extracted_at", "truncated", "headline_summary", "full_summary", "tags"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ArticleContent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item_tags in self.tags:
                if _item_tags:
                    _items.append(_item_tags.to_dict())
            _dict['tags'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ArticleContent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ok": obj.get("ok"),
            "url_hash": obj.get("url_hash"),
            "final_url": obj.get("final_url"),
            "image_url": obj.get("image_url"),
            "thumb_url": obj.get("thumb_url"),
            "video_url": obj.get("video_url"),
            "extracted_title": obj.get("extracted_title"),
            "text": obj.get("text"),
            "extracted_at": obj.get("extracted_at"),
            "truncated": obj.get("truncated"),
            "headline_summary": obj.get("headline_summary"),
            "full_summary": obj.get("full_summary"),
            "tags": [ArticleContentTagsInner.from_dict(_item) for _item in obj["tags"]] if obj.get("tags") is not None else None
        })
        return _obj


