# coding: utf-8

"""
    NewsRank API

    The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from newsrank_sdk.models.backtest_embedding_filter import BacktestEmbeddingFilter
from typing import Optional, Set
from typing_extensions import Self

class BacktestReplayWithEmbeddingsRequest(BaseModel):
    """
    BacktestReplayWithEmbeddingsRequest
    """ # noqa: E501
    var_from: StrictInt = Field(description="Start of time range (Unix milliseconds)", alias="from")
    to: StrictInt = Field(description="End of time range (Unix milliseconds)")
    topics: Optional[List[StrictStr]] = Field(default=None, description="Topic classes: `articles`, `stories`")
    categories: Optional[List[StrictStr]] = None
    sources: Optional[List[StrictStr]] = None
    keywords: Optional[List[StrictStr]] = None
    entities: Optional[List[StrictInt]] = None
    include_embeddings: Optional[StrictBool] = False
    embedding_filters: Optional[List[BacktestEmbeddingFilter]] = Field(default=None, description="Max 1 embedding filter per request")
    cursor: Optional[StrictInt] = 0
    limit: Optional[StrictInt] = 1000
    __properties: ClassVar[List[str]] = ["from", "to", "topics", "categories", "sources", "keywords", "entities", "include_embeddings", "embedding_filters", "cursor", "limit"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BacktestReplayWithEmbeddingsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in embedding_filters (list)
        _items = []
        if self.embedding_filters:
            for _item_embedding_filters in self.embedding_filters:
                if _item_embedding_filters:
                    _items.append(_item_embedding_filters.to_dict())
            _dict['embedding_filters'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BacktestReplayWithEmbeddingsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "from": obj.get("from"),
            "to": obj.get("to"),
            "topics": obj.get("topics"),
            "categories": obj.get("categories"),
            "sources": obj.get("sources"),
            "keywords": obj.get("keywords"),
            "entities": obj.get("entities"),
            "include_embeddings": obj.get("include_embeddings") if obj.get("include_embeddings") is not None else False,
            "embedding_filters": [BacktestEmbeddingFilter.from_dict(_item) for _item in obj["embedding_filters"]] if obj.get("embedding_filters") is not None else None,
            "cursor": obj.get("cursor") if obj.get("cursor") is not None else 0,
            "limit": obj.get("limit") if obj.get("limit") is not None else 1000
        })
        return _obj


