# coding: utf-8

"""
    NewsRank API

    The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class BacktestEvent(BaseModel):
    """
    BacktestEvent
    """ # noqa: E501
    id: Optional[StrictInt] = None
    ts: Optional[StrictInt] = Field(default=None, description="Event timestamp (Unix milliseconds)")
    event_type: Optional[StrictStr] = None
    cluster_id: Optional[StrictInt] = Field(default=None, description="Story cluster ID (0 for article-only events)")
    payload: Optional[Dict[str, Any]] = Field(default=None, description="The original WebSocket event payload")
    similarity: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Cosine similarity score (only present when embedding filter is active)")
    embedding: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, description="Embedding vector (only present when include_embeddings=true)")
    __properties: ClassVar[List[str]] = ["id", "ts", "event_type", "cluster_id", "payload", "similarity", "embedding"]

    @field_validator('event_type')
    def event_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['item.new', 'item.enriched', 'story.development', 'story.priority_changed', 'cluster.event', 'clusters.ranked']):
            raise ValueError("must be one of enum values ('item.new', 'item.enriched', 'story.development', 'story.priority_changed', 'cluster.event', 'clusters.ranked')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BacktestEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BacktestEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "ts": obj.get("ts"),
            "event_type": obj.get("event_type"),
            "cluster_id": obj.get("cluster_id"),
            "payload": obj.get("payload"),
            "similarity": obj.get("similarity"),
            "embedding": obj.get("embedding")
        })
        return _obj


