# coding: utf-8

"""
    NewsRank API

    The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EntityDetail(BaseModel):
    """
    EntityDetail
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    subcategory: Optional[StrictStr] = None
    slug: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    image_url: Optional[StrictStr] = None
    wikidata_id: Optional[StrictStr] = None
    wikipedia_url: Optional[StrictStr] = None
    article_count: Optional[StrictInt] = None
    aliases: Optional[List[StrictStr]] = None
    enriched: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["id", "name", "type", "subcategory", "slug", "description", "image_url", "wikidata_id", "wikipedia_url", "article_count", "aliases", "enriched"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['person', 'org', 'location']):
            raise ValueError("must be one of enum values ('person', 'org', 'location')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntityDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntityDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "subcategory": obj.get("subcategory"),
            "slug": obj.get("slug"),
            "description": obj.get("description"),
            "image_url": obj.get("image_url"),
            "wikidata_id": obj.get("wikidata_id"),
            "wikipedia_url": obj.get("wikipedia_url"),
            "article_count": obj.get("article_count"),
            "aliases": obj.get("aliases"),
            "enriched": obj.get("enriched")
        })
        return _obj


