# coding: utf-8

"""
    NewsRank API

    The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from newsrank_sdk.models.get_usage200_response_daily_inner import GetUsage200ResponseDailyInner
from newsrank_sdk.models.get_usage200_response_quota import GetUsage200ResponseQuota
from newsrank_sdk.models.get_usage200_response_summary import GetUsage200ResponseSummary
from typing import Optional, Set
from typing_extensions import Self

class GetUsage200Response(BaseModel):
    """
    GetUsage200Response
    """ # noqa: E501
    key_id: Optional[StrictStr] = None
    tier: Optional[StrictStr] = None
    quota: Optional[GetUsage200ResponseQuota] = None
    summary: Optional[GetUsage200ResponseSummary] = None
    daily: Optional[List[GetUsage200ResponseDailyInner]] = None
    __properties: ClassVar[List[str]] = ["key_id", "tier", "quota", "summary", "daily"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetUsage200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of quota
        if self.quota:
            _dict['quota'] = self.quota.to_dict()
        # override the default output from pydantic by calling `to_dict()` of summary
        if self.summary:
            _dict['summary'] = self.summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in daily (list)
        _items = []
        if self.daily:
            for _item_daily in self.daily:
                if _item_daily:
                    _items.append(_item_daily.to_dict())
            _dict['daily'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetUsage200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "key_id": obj.get("key_id"),
            "tier": obj.get("tier"),
            "quota": GetUsage200ResponseQuota.from_dict(obj["quota"]) if obj.get("quota") is not None else None,
            "summary": GetUsage200ResponseSummary.from_dict(obj["summary"]) if obj.get("summary") is not None else None,
            "daily": [GetUsage200ResponseDailyInner.from_dict(_item) for _item in obj["daily"]] if obj.get("daily") is not None else None
        })
        return _obj


