# coding: utf-8

"""
    NewsRank API

    The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from newsrank_sdk.models.graph_node import GraphNode
from typing import Optional, Set
from typing_extensions import Self

class GraphEdge(BaseModel):
    """
    GraphEdge
    """ # noqa: E501
    id: Optional[StrictInt] = None
    source_entity_id: Optional[StrictInt] = None
    target_entity_id: Optional[StrictInt] = None
    relationship_type: Optional[StrictStr] = None
    confidence: Optional[Union[StrictFloat, StrictInt]] = None
    article_count: Optional[StrictInt] = None
    source_entity: Optional[GraphNode] = None
    target_entity: Optional[GraphNode] = None
    __properties: ClassVar[List[str]] = ["id", "source_entity_id", "target_entity_id", "relationship_type", "confidence", "article_count", "source_entity", "target_entity"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GraphEdge from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of source_entity
        if self.source_entity:
            _dict['source_entity'] = self.source_entity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of target_entity
        if self.target_entity:
            _dict['target_entity'] = self.target_entity.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GraphEdge from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "source_entity_id": obj.get("source_entity_id"),
            "target_entity_id": obj.get("target_entity_id"),
            "relationship_type": obj.get("relationship_type"),
            "confidence": obj.get("confidence"),
            "article_count": obj.get("article_count"),
            "source_entity": GraphNode.from_dict(obj["source_entity"]) if obj.get("source_entity") is not None else None,
            "target_entity": GraphNode.from_dict(obj["target_entity"]) if obj.get("target_entity") is not None else None
        })
        return _obj


