# coding: utf-8

"""
    NewsRank API

    The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Item(BaseModel):
    """
    Item
    """ # noqa: E501
    id: Optional[StrictInt] = None
    url_hash: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    url: Optional[StrictStr] = None
    source_id: Optional[StrictInt] = None
    source_name: Optional[StrictStr] = None
    category: Optional[StrictStr] = None
    published_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp in milliseconds")
    discovered_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp in milliseconds")
    excerpt: Optional[StrictStr] = None
    image_url: Optional[StrictStr] = None
    content_status: Optional[StrictStr] = None
    headline_summary: Optional[StrictStr] = None
    slug: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "url_hash", "title", "url", "source_id", "source_name", "category", "published_at", "discovered_at", "excerpt", "image_url", "content_status", "headline_summary", "slug"]

    @field_validator('content_status')
    def content_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['has_content', 'no_content', 'failed']):
            raise ValueError("must be one of enum values ('has_content', 'no_content', 'failed')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Item from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Item from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "url_hash": obj.get("url_hash"),
            "title": obj.get("title"),
            "url": obj.get("url"),
            "source_id": obj.get("source_id"),
            "source_name": obj.get("source_name"),
            "category": obj.get("category"),
            "published_at": obj.get("published_at"),
            "discovered_at": obj.get("discovered_at"),
            "excerpt": obj.get("excerpt"),
            "image_url": obj.get("image_url"),
            "content_status": obj.get("content_status"),
            "headline_summary": obj.get("headline_summary"),
            "slug": obj.get("slug")
        })
        return _obj


