# coding: utf-8

"""
    NewsRank API

    The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class SourceRanking(BaseModel):
    """
    SourceRanking
    """ # noqa: E501
    source_id: Optional[StrictStr] = None
    source_name: Optional[StrictStr] = None
    logo_url: Optional[StrictStr] = None
    first_to_cluster_score: Optional[Union[StrictFloat, StrictInt]] = None
    cluster_frequency_score: Optional[Union[StrictFloat, StrictInt]] = None
    speed_score: Optional[Union[StrictFloat, StrictInt]] = None
    topical_authority_score: Optional[Union[StrictFloat, StrictInt]] = None
    content_diversity_score: Optional[Union[StrictFloat, StrictInt]] = None
    extraction_success_score: Optional[Union[StrictFloat, StrictInt]] = None
    neutrality_score: Optional[Union[StrictFloat, StrictInt]] = None
    sensationalism_score: Optional[Union[StrictFloat, StrictInt]] = None
    reliability_score: Optional[Union[StrictFloat, StrictInt]] = None
    overall_score: Optional[Union[StrictFloat, StrictInt]] = None
    tier: Optional[StrictStr] = None
    description_one_liner: Optional[StrictStr] = None
    description_summary: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["source_id", "source_name", "logo_url", "first_to_cluster_score", "cluster_frequency_score", "speed_score", "topical_authority_score", "content_diversity_score", "extraction_success_score", "neutrality_score", "sensationalism_score", "reliability_score", "overall_score", "tier", "description_one_liner", "description_summary"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SourceRanking from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SourceRanking from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "source_id": obj.get("source_id"),
            "source_name": obj.get("source_name"),
            "logo_url": obj.get("logo_url"),
            "first_to_cluster_score": obj.get("first_to_cluster_score"),
            "cluster_frequency_score": obj.get("cluster_frequency_score"),
            "speed_score": obj.get("speed_score"),
            "topical_authority_score": obj.get("topical_authority_score"),
            "content_diversity_score": obj.get("content_diversity_score"),
            "extraction_success_score": obj.get("extraction_success_score"),
            "neutrality_score": obj.get("neutrality_score"),
            "sensationalism_score": obj.get("sensationalism_score"),
            "reliability_score": obj.get("reliability_score"),
            "overall_score": obj.get("overall_score"),
            "tier": obj.get("tier"),
            "description_one_liner": obj.get("description_one_liner"),
            "description_summary": obj.get("description_summary")
        })
        return _obj


