# coding: utf-8

"""
    NewsRank API

    The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class StoryDevelopment(BaseModel):
    """
    StoryDevelopment
    """ # noqa: E501
    id: Optional[StrictInt] = None
    cluster_id: Optional[StrictInt] = None
    created_at_ms: Optional[StrictInt] = Field(default=None, description="Unix timestamp in milliseconds")
    title: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    significance: Optional[StrictStr] = None
    previous_headline: Optional[StrictStr] = None
    new_headline: Optional[StrictStr] = None
    trigger_article_hashes: Optional[List[StrictStr]] = None
    enrichment_seq: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["id", "cluster_id", "created_at_ms", "title", "description", "significance", "previous_headline", "new_headline", "trigger_article_hashes", "enrichment_seq"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StoryDevelopment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StoryDevelopment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "cluster_id": obj.get("cluster_id"),
            "created_at_ms": obj.get("created_at_ms"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "significance": obj.get("significance"),
            "previous_headline": obj.get("previous_headline"),
            "new_headline": obj.get("new_headline"),
            "trigger_article_hashes": obj.get("trigger_article_hashes"),
            "enrichment_seq": obj.get("enrichment_seq")
        })
        return _obj


