# coding: utf-8

"""
    NewsRank API

    The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from newsrank_sdk.models.story_update_signal_new_articles_inner import StoryUpdateSignalNewArticlesInner
from typing import Optional, Set
from typing_extensions import Self

class StoryUpdateSignal(BaseModel):
    """
    StoryUpdateSignal
    """ # noqa: E501
    cluster_id: Optional[StrictInt] = None
    new_articles: Optional[List[StoryUpdateSignalNewArticlesInner]] = None
    new_article_count: Optional[StrictInt] = None
    new_sources: Optional[List[StrictStr]] = None
    new_entities: Optional[List[StrictStr]] = None
    significance: Optional[StrictStr] = None
    significance_reasons: Optional[List[StrictStr]] = None
    baseline_member_count: Optional[StrictInt] = None
    checked_at_ms: Optional[StrictInt] = Field(default=None, description="Unix timestamp in milliseconds")
    __properties: ClassVar[List[str]] = ["cluster_id", "new_articles", "new_article_count", "new_sources", "new_entities", "significance", "significance_reasons", "baseline_member_count", "checked_at_ms"]

    @field_validator('significance')
    def significance_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'minor', 'moderate', 'major']):
            raise ValueError("must be one of enum values ('none', 'minor', 'moderate', 'major')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StoryUpdateSignal from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in new_articles (list)
        _items = []
        if self.new_articles:
            for _item_new_articles in self.new_articles:
                if _item_new_articles:
                    _items.append(_item_new_articles.to_dict())
            _dict['new_articles'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StoryUpdateSignal from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cluster_id": obj.get("cluster_id"),
            "new_articles": [StoryUpdateSignalNewArticlesInner.from_dict(_item) for _item in obj["new_articles"]] if obj.get("new_articles") is not None else None,
            "new_article_count": obj.get("new_article_count"),
            "new_sources": obj.get("new_sources"),
            "new_entities": obj.get("new_entities"),
            "significance": obj.get("significance"),
            "significance_reasons": obj.get("significance_reasons"),
            "baseline_member_count": obj.get("baseline_member_count"),
            "checked_at_ms": obj.get("checked_at_ms")
        })
        return _obj


