# coding: utf-8

"""
    NewsRank API

    The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Story(BaseModel):
    """
    Story
    """ # noqa: E501
    id: Optional[StrictInt] = None
    slug: Optional[StrictStr] = None
    headline: Optional[StrictStr] = None
    summary: Optional[StrictStr] = None
    image_url: Optional[StrictStr] = None
    article_count: Optional[StrictInt] = None
    sources: Optional[List[StrictStr]] = None
    top_entities: Optional[List[StrictStr]] = None
    category: Optional[StrictStr] = None
    first_seen: Optional[StrictInt] = Field(default=None, description="Unix timestamp in milliseconds")
    last_updated: Optional[StrictInt] = Field(default=None, description="Unix timestamp in milliseconds")
    label: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "slug", "headline", "summary", "image_url", "article_count", "sources", "top_entities", "category", "first_seen", "last_updated", "label"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Story from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Story from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "slug": obj.get("slug"),
            "headline": obj.get("headline"),
            "summary": obj.get("summary"),
            "image_url": obj.get("image_url"),
            "article_count": obj.get("article_count"),
            "sources": obj.get("sources"),
            "top_entities": obj.get("top_entities"),
            "category": obj.get("category"),
            "first_seen": obj.get("first_seen"),
            "last_updated": obj.get("last_updated"),
            "label": obj.get("label")
        })
        return _obj


