# coding: utf-8

"""
    NewsRank API

    The NewsRank API provides programmatic access to real-time news articles, stories, entities, and search across thousands of sources.  All endpoints return JSON. Paginated endpoints include `total`, `offset`, and `limit` fields in the response. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class VectorSearch200ResponseStoriesInner(BaseModel):
    """
    VectorSearch200ResponseStoriesInner
    """ # noqa: E501
    similarity: Optional[Union[StrictFloat, StrictInt]] = None
    distance: Optional[Union[StrictFloat, StrictInt]] = None
    cluster_id: Optional[StrictInt] = None
    headline: Optional[StrictStr] = None
    summary: Optional[StrictStr] = None
    article_count: Optional[StrictInt] = None
    first_seen: Optional[StrictInt] = None
    last_updated: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["similarity", "distance", "cluster_id", "headline", "summary", "article_count", "first_seen", "last_updated"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VectorSearch200ResponseStoriesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VectorSearch200ResponseStoriesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "similarity": obj.get("similarity"),
            "distance": obj.get("distance"),
            "cluster_id": obj.get("cluster_id"),
            "headline": obj.get("headline"),
            "summary": obj.get("summary"),
            "article_count": obj.get("article_count"),
            "first_seen": obj.get("first_seen"),
            "last_updated": obj.get("last_updated")
        })
        return _obj


